# Copyright (c) 2023-2025 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Pimoroni Trackball (PIM447) I2C sensor
compatible: "pimoroni,trackball"

include: [sensor-device.yaml, i2c-device.yaml]

properties:
  reg:
    required: true
    
  label:
    required: false
