# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

description: Pimoroni Trackball I2C

compatible: "pimoroni,trackball"

include: [sensor-device.yaml, i2c-device.yaml]

properties:
  label:
    required: true