# SPDX-License-Identifier: MIT

description: Pimoroni Trackball I2C pointing device for ZMK

compatible: "pimoroni,trackball"

include: i2c-device.yaml

properties:
  label:
    type: string
    required: true
    description: Human readable string describing the device
  
  resolution:
    type: int
    default: 400
    description: Sensor resolution in counts per inch
    
  invert-x:
    type: boolean
    description: Invert X axis movement
    
  invert-y:
    type: boolean
    description: Invert Y axis movement