file_format: "1"
id: rickKlor
name: Rick Klor
type: shield
url: https://github.com/menneric84/rick-klor/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - pointing
siblings:
  - rickKlorLeft
  - rickKlorRight